source "https://rubygems.org"
gem "jekyll"
gem "minima"

group :jekyll_plugins do
  gem "jekyll-feed", "~> 0.12"
end

# platforms :mingw, :x64_mingw, :mswin, :jruby do
#   gem "tzinfo"
#   gem "tzinfo-data"
# end

# gem "wdm", :platforms => [:mingw, :x64_mingw, :mswin]